name = "MAGE_SKIMAGE_MEASURE"
uuid = "ca5378d6-e425-4eb1-a567-c0f7d8b11b15"
authors = ["Camilo De La Torre <camilo.de-la-torre@ut-capitole.fr> and contributors"]
version = "1.1.0-DEV"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedArrays = "aaf54ef3-cdf8-58ed-94cc-d582ad619b94"
DistributedNext = "fab6aee4-877b-4bac-a744-3eca44acbb6f"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SearchNetworks = "17666995-d420-48ac-8d7c-8a155fef8e5d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UTCGP = "956831e1-0a7a-492a-ae16-058c6128a9f2"

[compat]
DistributedNext = ">=1.1.0"
ImageMorphology = ">=0.4.6"
TestImages = ">=1.9.0"
julia = ">=1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
